"""update

Revision ID: 1baa2b7f059b
Revises: 
Create Date: 2025-01-09 19:00:44.257438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1baa2b7f059b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('nickname', sa.String(), server_default='dummy', nullable=False))
    op.alter_column('ideas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('avatar_filename', sa.String(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'MODER', name='userrole'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'is_logged_in')
    op.drop_column('users', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_logged_in', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(), server_default=sa.text("'None'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('USER', 'ADMIN', 'MODER', name='userrole'),
               existing_nullable=False)
    op.drop_column('users', 'avatar_filename')
    op.alter_column('ideas', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('ideas', 'nickname')
    # ### end Alembic commands ###
